### ISSUE TITLE
Error on put-metric-data API call

### ISSUE THREAD

**Issue by jpf5064** [awsimaya/PetAdoptions#52]
Admin:~/environment/workshopfiles/PetAdoptions/cdk/pet_stack (master) $ aws cloudwatch put-metric-data --metric-name throttlecount --namespace observabilityworkshop --unit counter --value 156 --dimensions ServerName=DemoServer,ServerType=A1

An error occurred (InvalidParameterValue) when calling the PutMetricData operation: The parameter MetricData.member.1.Unit must be a value in the set [ Seconds, Microseconds, Milliseconds, Bytes, Kilobytes, Megabytes, Gigabytes, Terabytes, Bits, Kilobits, Megabits, Gigabits, Terabits, Percent, Count, Bytes/Second, Kilobytes/Second, Megabytes/Second, Gigabytes/Second, Terabytes/Second, Bits/Second, Kilobits/Second, Megabits/Second, Gigabits/Second, Terabits/Second, Count/Second, None ].

**Comment by awsimaya** [comment]
Fixed and deployed the changes.
